### ISSUE TITLE
Getting prompted for Docker's password on vagrant up

### ISSUE THREAD

**Issue by KorvinSzanto** [czettnersandor/vagrant-docker-lamp#1]
On vagrant up, I'm seeing this:

```
    default: The machine you're rsyncing folders to is configured to use
    default: password-based authentication. Vagrant can't script rsync to automatically
    default: enter this password, so you'll likely be prompted for a password
    default: shortly.
    default:
    default: If you don't want to have to do this, please enable automatic
    default: key insertion using `config.ssh.insert_key`.
    default: Rsyncing folder: /git/fieldblogger_web/ => /var/lib/docker/docker_1443720491_99939
docker@127.0.0.1's password:
```

I enabled key insertion in my VagrantFile, but it didn't seem to do the trick. Any ideas?
